"""Inintial migration

Revision ID: 264cff84f1dc
Revises: 
Create Date: 2023-11-13 11:54:48.843110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264cff84f1dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
